#%RAML 1.0 Library

resourceTypes:
  collection:
     get:
      responses:
        200:
        400:
        401:
        405:
        415:
        429:
        500:
     post:
      responses:
        201:
        400:
        401:
        405:
        415:
        429:
        500:

  item:
     get:
      responses:
        200:
        400:
        401:
        405:
        415:
        429:
        500:
     put:
      responses:
        200:
        201:
        304:
        400:
        401:
        405:
        415:
        429:
        500:
     delete:
      responses:
        200:
        202:
        400:
        401:
        405:
        415:
        429:
        500: